//
//  Markers.swift
//  Beev
//
//  Created by Maria Concetta on 09/05/24.
//


import SwiftUI
import CoreLocation

// Marker struct
struct Marker: Identifiable {
    let id = UUID()
    let name: String
    let coordinate: CLLocationCoordinate2D
}


let markers: [Marker] = [
    Marker(name: "Fountain 1", coordinate: .fountain1),
    Marker(name: "Fountain 2", coordinate: .fountain2),
    Marker(name: "Fountain 3", coordinate: .fountain3),
    Marker(name: "Fountain 4", coordinate: .fountain4),
    Marker(name: "Fountain 5", coordinate: .fountain5),
    Marker(name: "Fountain 6", coordinate: .fountain6),
    Marker(name: "Fountain 7", coordinate: .fountain7),
    Marker(name: "Fountain 8", coordinate: .fountain8),
    Marker(name: "Fountain 9", coordinate: .fountain9),
    Marker(name: "Fountain 10", coordinate: .fountain10),
    Marker(name: "Fountain 11", coordinate: .fountain11),
    Marker(name: "Fountain 12", coordinate: .fountain12),
    Marker(name: "Fountain 13", coordinate: .fountain13),
    Marker(name: "Fountain 14", coordinate: .fountain14),
    Marker(name: "Fountain 15", coordinate: .fountain15),
    Marker(name: "Fountain 16", coordinate: .fountain16),
    Marker(name: "Fontana Romana", coordinate: .fontanaRomana),
    Marker(name: "Fountain 17", coordinate: .fountain17),
    Marker(name: "Fountain 18", coordinate: .fountain18),
    Marker(name: "Fountain 19", coordinate: .fountain19),
    Marker(name: "Fountain 20", coordinate: .fountain20),
    Marker(name: "Fountain 21", coordinate: .fountain21),
    Marker(name: "Fountain 22", coordinate: .fountain22),
    Marker(name: "Fountain 23", coordinate: .fountain23),
    Marker(name: "Fountain 24", coordinate: .fountain24),
    Marker(name: "Fountain 25", coordinate: .fountain25),
    Marker(name: "Fountain 26", coordinate: .fountain26),
    Marker(name: "Fountain 27", coordinate: .fountain27),
    Marker(name: "Fountain 28", coordinate: .fountain28),
    Marker(name: "Fountain 29", coordinate: .fountain29),
    Marker(name: "Fountain 30", coordinate: .fountain30),
    Marker(name: "Fountain 31", coordinate: .fountain31),
    Marker(name: "Fountain 32", coordinate: .fountain32),
    Marker(name: "Fountain 33", coordinate: .fountain33),
    Marker(name: "Fountain 34", coordinate: .fountain34),
    Marker(name: "Fountain 35", coordinate: .fountain35),
    Marker(name: "Fountain 36", coordinate: .fountain36),
    Marker(name: "Fountain 37", coordinate: .fountain37),
    Marker(name: "Fountain 38", coordinate: .fountain38),
    Marker(name: "Fountain 39", coordinate: .fountain39),
    Marker(name: "Fountain 40", coordinate: .fountain40),
    Marker(name: "Fountain 41", coordinate: .fountain41),
    Marker(name: "Fountain 42", coordinate: .fountain42),
    Marker(name: "Fountain 43", coordinate: .fountain43),
    Marker(name: "Fountain 44", coordinate: .fountain44),
    Marker(name: "Fountain 45", coordinate: .fountain45),
    Marker(name: "Fountain 46", coordinate: .fountain46),
    Marker(name: "Fountain 47", coordinate: .fountain47),
    Marker(name: "Fountain 48", coordinate: .fountain48),
    Marker(name: "Fountain 49", coordinate: .fountain49),
    Marker(name: "Fountain 50", coordinate: .fountain50),
    Marker(name: "Fountain 51", coordinate: .fountain51),
    Marker(name: "Fountain 52", coordinate: .fountain52),
    Marker(name: "Fountain 53", coordinate: .fountain53),
    Marker(name: "Fountain 54", coordinate: .fountain54),
    Marker(name: "Fountain 55", coordinate: .fountain55),
    Marker(name: "Fountain 56", coordinate: .fountain56),
    Marker(name: "Fountain 57", coordinate: .fountain57),
    Marker(name: "Fountain 58", coordinate: .fountain58),
    Marker(name: "Fountain 59", coordinate: .fountain59),
    Marker(name: "Fountain 60", coordinate: .fountain60),
    Marker(name: "Fountain 61", coordinate: .fountain61),
    Marker(name: "Fountain 62", coordinate: .fountain62),
    Marker(name: "Fountain 63", coordinate: .fountain63),
    Marker(name: "Fountain 64", coordinate: .fountain64),
    Marker(name: "Fountain 65", coordinate: .fountain65),
    Marker(name: "Fountain 66", coordinate: .fountain66),
    Marker(name: "Fountain 67", coordinate: .fountain67),
    Marker(name: "Fountain 68", coordinate: .fountain68),
    Marker(name: "Fountain 69", coordinate: .fountain69),
    Marker(name: "Fountain 70", coordinate: .fountain70),
    Marker(name: "Fountain 71", coordinate: .fountain71),
    Marker(name: "Fountain 72", coordinate: .fountain72),
    Marker(name: "Fountain 73", coordinate: .fountain73),
    Marker(name: "Fountain 74", coordinate: .fountain74),
    Marker(name: "Fountain 75", coordinate: .fountain75),
    Marker(name: "Fountain 76", coordinate: .fountain76),
    Marker(name: "Fountain 77", coordinate: .fountain77),
    Marker(name: "Fountain 78", coordinate: .fountain78),
    Marker(name: "Fountain 79", coordinate: .fountain79),
    Marker(name: "Fountain 80", coordinate: .fountain80),
    Marker(name: "Fountain 81", coordinate: .fountain81),
    Marker(name: "Fountain 82", coordinate: .fountain82),
    Marker(name: "Fountain 83", coordinate: .fountain83),
    Marker(name: "Fountain 84", coordinate: .fountain84),
    Marker(name: "Fountain 85", coordinate: .fountain85),
    Marker(name: "Fountain 86", coordinate: .fountain86),
    Marker(name: "Fountain 87", coordinate: .fountain87),
    Marker(name: "Fountain 88", coordinate: .fountain88),
    Marker(name: "Fountain 89", coordinate: .fountain89),
    Marker(name: "Fountain 90", coordinate: .fountain90),
    Marker(name: "Fountain 91", coordinate: .fountain91),
    Marker(name: "Fountain 92", coordinate: .fountain92),
    Marker(name: "Fountain 93", coordinate: .fountain93),
    Marker(name: "Fountain 94", coordinate: .fountain94),
    Marker(name: "Fountain 95", coordinate: .fountain95),
    Marker(name: "Fountain 96", coordinate: .fountain96),
    Marker(name: "Fountain 97", coordinate: .fountain97),
    Marker(name: "Fountain 98", coordinate: .fountain98),
    Marker(name: "Fountain 99", coordinate: .fountain99),
    Marker(name: "Fountain 100", coordinate: .fountain100),
    Marker(name: "Fountain 101", coordinate: .fountain101),
    Marker(name: "Fountain 102", coordinate: .fountain102),
    Marker(name: "Fountain 103", coordinate: .fountain103),
    Marker(name: "Fountain 104", coordinate: .fountain104),
    Marker(name: "Fountain 105", coordinate: .fountain105),
    Marker(name: "Fountain 106", coordinate: .fountain106),
    Marker(name: "Fountain 107", coordinate: .fountain107),
    Marker(name: "Fountain 108", coordinate: .fountain108),
    Marker(name: "Fountain 109", coordinate: .fountain109),
    Marker(name: "Fountain 110", coordinate: .fountain110),
    Marker(name: "Fountain 111", coordinate: .fountain111),
    Marker(name: "Fountain 112", coordinate: .fountain112),
    Marker(name: "Fountain 113", coordinate: .fountain113),
    Marker(name: "Fountain 114", coordinate: .fountain114),
    Marker(name: "Fountain 115", coordinate: .fountain115),
    Marker(name: "Fountain 116", coordinate: .fountain116),
    Marker(name: "Fountain 117", coordinate: .fountain117),
    Marker(name: "Fountain 118", coordinate: .fountain118),
    Marker(name: "Fountain 119", coordinate: .fountain119),
    Marker(name: "Fountain 120", coordinate: .fountain120),
    Marker(name: "Fountain 121", coordinate: .fountain121),
    Marker(name: "Fountain 122", coordinate: .fountain122),
    Marker(name: "Fountain 123", coordinate: .fountain123),
    Marker(name: "Fountain 124", coordinate: .fountain124),
    Marker(name: "Fountain 125", coordinate: .fountain125),
    Marker(name: "Fountain 126", coordinate: .fountain126),
    Marker(name: "Fountain 127", coordinate: .fountain127),
    Marker(name: "Fountain 128", coordinate: .fountain128),
    Marker(name: "Fountain 129", coordinate: .fountain129),
    Marker(name: "Fountain 130", coordinate: .fountain130),
    Marker(name: "Fountain 131", coordinate: .fountain131),
    Marker(name: "Fountain 132", coordinate: .fountain132),
    Marker(name: "Fountain 133", coordinate: .fountain133),
    Marker(name: "Fountain 134", coordinate: .fountain134),
    Marker(name: "Fountain 135", coordinate: .fountain135),
    Marker(name: "Fountain 136", coordinate: .fountain136),
    Marker(name: "Fountain 137", coordinate: .fountain137),
    Marker(name: "Fountain 138", coordinate: .fountain138),
    Marker(name: "Fountain 139", coordinate: .fountain139),
    Marker(name: "Fountain 140", coordinate: .fountain140),
    Marker(name: "Fountain 141", coordinate: .fountain141),
    Marker(name: "Fountain 142", coordinate: .fountain142),
    Marker(name: "Fountain 143", coordinate: .fountain143),
    Marker(name: "Fountain 144", coordinate: .fountain144),
    Marker(name: "Fountain 145", coordinate: .fountain145),
    Marker(name: "Fountain 146", coordinate: .fountain146),
    Marker(name: "Fountain 147", coordinate: .fountain147),
    Marker(name: "Fountain 148", coordinate: .fountain148),
    Marker(name: "Fountain 149", coordinate: .fountain149),
    Marker(name: "Fountain 150", coordinate: .fountain150)
]

